DROP TABLE IF EXISTS DIST_INT_ENER_ELE_CONSOLIDADO;

CREATE TABLE DIST_INT_ENER_ELE_CONSOLIDADO AS
SELECT NomAgente,SigAgente,NumCPFCNPJ,IdeConjuntoUnidadeConsumidora,DscAlimentadorSubestacao,DscSubestacaoDistribuicao,NumOrdemInterrupcao,DscTipoInterrupcao,IdeMotivoExpurgo,DatInicioInterrupcao,DatFimInterrupcao,FatGeradorInterrupcao,NumNivelTensao,NumUnidadeConsumidora,NumConsumidorConjunto,NumAno
FROM(
	(SELECT *
		FROM(
			SELECT NomAgente,SigAgente,NumCPFCNPJ,IdeConjuntoUnidadeConsumidora,DscAlimentadorSubestacao,DscSubestacaoDistribuicao,NumOrdemInterrupcao,DscTipoInterrupcao,IdeMotivoExpurgo,DatInicioInterrupcao,DatFimInterrupcao,FatGeradorInterrupcao,NumNivelTensao,NumUnidadeConsumidora,NumConsumidorConjunto,NumAno FROM DIST_INT_ENER_ELE_2017
			UNION
			SELECT NomAgente,SigAgente,NumCPFCNPJ,IdeConjuntoUnidadeConsumidora,DscAlimentadorSubestacao,DscSubestacaoDistribuicao,NumOrdemInterrupcao,DscTipoInterrupcao,IdeMotivoExpurgo,DatInicioInterrupcao,DatFimInterrupcao,FatGeradorInterrupcao,NumNivelTensao,NumUnidadeConsumidora,NumConsumidorConjunto,NumAno FROM DIST_INT_ENER_ELE_2018
			UNION
			SELECT NomAgente,SigAgente,NumCPFCNPJ,IdeConjuntoUnidadeConsumidora,DscAlimentadorSubestacao,DscSubestacaoDistribuicao,NumOrdemInterrupcao,DscTipoInterrupcao,IdeMotivoExpurgo,DatInicioInterrupcao,DatFimInterrupcao,FatGeradorInterrupcao,NumNivelTensao,NumUnidadeConsumidora,NumConsumidorConjunto,NumAno FROM DIST_INT_ENER_ELE_2019
			UNION
			SELECT NomAgente,SigAgente,NumCPFCNPJ,IdeConjuntoUnidadeConsumidora,DscAlimentadorSubestacao,DscSubestacaoDistribuicao,NumOrdemInterrupcao,DscTipoInterrupcao,IdeMotivoExpurgo,DatInicioInterrupcao,DatFimInterrupcao,FatGeradorInterrupcao,NumNivelTensao,NumUnidadeConsumidora,NumConsumidorConjunto,NumAno FROM DIST_INT_ENER_ELE_2020
			UNION
			SELECT NomAgente,SigAgente,NumCPFCNPJ,IdeConjuntoUnidadeConsumidora,DscAlimentadorSubestacao,DscSubestacaoDistribuicao,NumOrdemInterrupcao,DscTipoInterrupcao,IdeMotivoExpurgo,DatInicioInterrupcao,DatFimInterrupcao,FatGeradorInterrupcao,NumNivelTensao,NumUnidadeConsumidora,NumConsumidorConjunto,NumAno FROM DIST_INT_ENER_ELE_2021)))
		